version: "3"
volumes:
  kong_data:
    driver: local
services:
  # Custom Auth service to be deployed so that Kong can communicate with for auth
  soapechoservice:
    build:
      context: ./soap-echo-service
      dockerfile: Dockerfile
    container_name: soapechoservice
    ports:
      - "8080:8080"
    networks:
      - kong-ee

  # Postgresql DB for Kong Manager - Traditional mode
  postgres:
    image: postgres:13
    restart: always
    container_name: kong-postgres
    networks:
      - kong-ee
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: kong
    volumes:
      - kong_data:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"

  # Running the migrations here
  kong-migrations:
    image: kong/kong-gateway:3.7.0.0
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PASSWORD: admin
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: kong-postgres
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
    links:
      - postgres:postgres
    networks:
      - kong-ee
    restart: on-failure
  kong:
    image: kong/kong-gateway:3.7.0.0
    user: kong
    container_name: kong
    networks:
      - kong-ee
    depends_on:
      - kong-migrations
    restart: on-failure
    ports:
      - "8000-8006:8000-8006/tcp"
      - "8100:8100/tcp"
      - "8443-8447:8443-8447/tcp"
      - "9080:9080/tcp"
    environment:
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}

      ## GENERAL
      KONG_AUDIT_LOG: on
      KONG_LOG_LEVEL: error
      KONG_PLUGINS: bundled,myplugin # add the plugin you've built here in this line

      ## NGINX
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_STREAM_LISTEN: "0.0.0.0:5555 reuseport backlog=65536, 0.0.0.0:5556 reuseport backlog=65536"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_STATUS_LISTEN: "0.0.0.0:8100"
      KONG_NGINX_WORKER_PROCESSES: 1

      ## DATASTORE
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-postgres
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}

      ## KONG MANAGER
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_ADMIN_GUI_API_URL: http://localhost:8001

      ## MISCELLANEOUS
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: "system"
      KONG_LUA_PACKAGE_PATH: /opt/conf/?.lua;

      KONG_CLIENT_BODY_BUFFER_SIZE: 1024k

      # Use this password to login to Kong Manager. Username is kong_admin
      KONG_PASSWORD: admin

    volumes:
      # Copy the files in the my-plugin folder into the docker-compose process when deploying the Kong gateway as part of migrations
      - ./my-plugin:/opt/conf/
networks:
  kong-ee:
    driver: bridge
